version: '3.8'

services:
  db:
    container_name: ex-64
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - '4000:5432'
    volumes:
      - './db:/var/lib/postgresql/data'

volumes:
  db:
    driver: local